# Generated by Django 5.1.5 on 2025-04-05 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relative_students',
            field=models.ManyToManyField(blank=True, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
