# Generated by Django 5.1.1 on 2025-01-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderproducts',
            name='user',
        ),
    ]
