# Generated by Django 5.1.1 on 2025-01-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cartorderproducts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('packaging', 'Packing'), ('Ready To Pickup', 'Ready To Pickup'), ('All Ready Pickup', 'Has been Pickup')], default='processing', max_length=30),
        ),
    ]
