# Generated by Django 5.1.1 on 2025-01-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartorderproducts_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderproducts',
            old_name='invoice_no',
            new_name='order_no',
        ),
    ]
