# Generated by Django 5.1.5 on 2025-02-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producttag_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.producttag'),
        ),
    ]
