# Generated by Django 5.1.5 on 2025-04-04 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tracking_website_address',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
