# Generated by Django 5.1.5 on 2025-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cartorder_shipping_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorderproducts',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=12),
        ),
    ]
